export const string = {
  login: "login",
  Login: "Login",
  login2: "Lorem Ipsum is simply",
  login3: "Lorem Ipsum is simply",
  loginEmail: "Log in with",
  enterEmail: "Enter email",
  EnteryourPassword: "Enter your Password",
  EnterPassword: "Enter password",
  logindesc: "Welcome Back,you have been missed!",
  RememberMe: "Remember Me",
  Forgetpassword: "Forget password ?",
  otpTitle: "Verification Code",
  otpdesc: "Please enter the code sent to ",
  enterCode: "Enter code",
  Submit: "Submit",
  ResendCode: "Resend Code",
  DidntrecieveCode: "Did'nt recieve the code?",
  Confirm: "Confirm",
};
