// export const icons: Record<string, { uri: string }> = {
//   arrowBack_Icon: { uri: "material/icons/arrowBackIcon.png" },
//   modalIconOtp: { uri: "material/icons/modalotpIcon.png" },
//   drawertabdashboardIcon: require('./element.png') ,
//   drawertabUsersIcon: { uri: "material/icons/profile-2user.png" },
//   drawertabLawIcon: { uri: "material/icons/LAw.png" },
//   drawertabnoteIcon: { uri: "material/icons/note.png" },
//   drawertabstarsupIcon: { uri: "material/icons/status-up.png" },
//   drawertabJobIcon: { uri: "material/icons/job.png" },
//   searchBarIcon: { uri: "material/icons/search-normal.png" },
//   profileHeaderBellIcon: { uri: "material/icons/Vector.png" },
//   tableDeleteIcon: { uri: "material/icons/Trash can.png" },
//   tableEditIcon: { uri: "material/icons/Edit 1.png" },
//   tableReadIcon: { uri: "material/icons/Trash can copy.png" },
//   tableStatusIcon: { uri: "material/icons/_Badge base.png" },
//   screenHeaderPlusIcon: { uri: "material/icons/Plus.png" },
//   screenHeaderFilterIcon: { uri: "material/icons/filter.png" },
//   tablepaginationleftarrowIcon: { uri: "material/icons/ArrowLineLeft2.png" },
//   tablepaginationrightarrowIcon: { uri: "material/icons/ArrowLineRight2.png" },
//   editPencilicon: { uri: "material/icons/edit-pencil.png" },
//   documentDownloadIcon: { uri: "material/icons/Download 2.png" },
//   documendPdfIcon: { uri: "material/icons/Frame 1686557330.png" },
//   trendupIcon: { uri: "material/icons/trend-up.png" },
//   dashboardButtonNewscardIcon: { uri: "material/icons/Frame 1597887482.png" },
//   Drop_Down_Icon_Down:{uri:'material/icons/Icon - Graphics.png'},
//   HeaderFeedBackIcon:{uri:'material/icons/Chat alt 2.png'}
// };
export const icons: Record<string, { uri: string }> = {
  // arrowBack_Icon: require("./ba"),
  modalIconOtp: require("./modalotpIcon.png"),
  drawertabdashboardIcon: require("./element.png"),
  drawertabUsersIcon: require("./profile-2user.png"),
  drawertabLawIcon: require("./LAw.png"),
  drawertabnoteIcon: require("./note.png"),
  drawertabstarsupIcon: require("./status-up.png"),
  drawertabJobIcon: require("./job.png"),
  searchBarIcon: require("./search-normal.png"),
  profileHeaderBellIcon: require("./Vector.png"),
  tableDeleteIcon: require("./Trash can.png"),
  tableEditIcon: require("./Edit 1.png"),
  tableReadIcon: require("./Trash can copy.png"),
  tableStatusIcon: require("./_Badge base.png"),
  tableEyeIcon: require("./Eye.png"),
  tableDocumentIcon: require("./document-text.png"),
  screenHeaderPlusIcon: require("./Plus.png"),
  screenHeaderFilterIcon: require("./filter.png"),
  tablepaginationleftarrowIcon: require("./ArrowLineLeft2.png"),
  tablepaginationrightarrowIcon: require("./ArrowLineRight2.png"),
  editPencilicon: require("./edit-pencil.png"),
  documentDownloadIcon: require("./Download 2.png"),
  documendPdfIcon: require("./Frame 1686557330.png"),
  trendupIcon: require("./trend-up.png"),
  dashboardButtonNewscardIcon: require("./Frame 1597887482.png"),
  Drop_Down_Icon_Down: require("./Icon - Graphics.png"),
  HeaderFeedBackIcon: require("./Chat alt 2.png"),
};
