import { StyleSheet } from "react-native";
import { MontserratRegular, PoppinsRegular } from "../../Resources/fonts";
import helpers from "../../utils/helpers";

export const styles = StyleSheet.create({
  custom4: {
    flexGrow: 1,
    backgroundColor: "#F3F6FB",
    paddingBottom: 40,
  },
  custom3: {
    marginHorizontal: 25,
    marginTop: 20,
  },
  custom1: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  custom2: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
  },
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: "#ffffff",
    borderRadius: 12,
  },
  inputContainer: {
    padding: 14,
    borderRadius: 10,
    fontSize: 16,
    backgroundColor: "#F0F2F5",
    fontFamily: PoppinsRegular,
    color: "#2C2C2D",
    marginBottom: 16,
  },
  descriptionContainer: {
    marginTop: 8,
  },
  inputField: {
    padding: 15,
    minHeight: 120,
    backgroundColor: "#F0F2F5",
    borderRadius: 10,
    fontSize: 14,
    fontFamily: PoppinsRegular,
    color: "#2C2C2D",
  },
  rowContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  dateContainer: {
    borderRadius: 8,
    backgroundColor: "#F0F2F5",
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginLeft: 10,
  },
  date: {
    fontSize: 14,
    color: "#2C2C2D",
    fontFamily: PoppinsRegular,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "600",
    marginBottom: 12,
    color: "#1C1C1E",
    fontFamily: PoppinsRegular,
  },
  userRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    paddingHorizontal: 5,
  },
  customText: {
    fontSize: 14,
    fontFamily: PoppinsRegular,
    color: "#2C2C2D",
  },
  custom5: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 16,
    marginTop: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  custom6: {
    marginTop: 10,
  },
  custom7: {
    marginTop: 30,
    marginHorizontal: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  custom8: {
    backgroundColor: "#EDEDED",
    padding: 8,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  custom9: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  files: {
    fontSize: 14,
    fontWeight: "500",
    fontFamily: PoppinsRegular,
    color: "#2C2C2D",
  },
  buttonfile: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0F3D3E",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  desc1: {
    fontSize: 15,
    fontFamily: PoppinsRegular,
    color: "#FFFFFF",
    fontWeight: "500",
  },
});
