import { StyleSheet } from "react-native";
import helpers from "../../../utils/helpers";
import { PoppinsRegular } from "../../../Resources/fonts";

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContainer: {
    width: 550,
    height: 680,
    backgroundColor: "white",
    padding: 15,
    borderRadius: 10,
    justifyContent: "space-between",
  },
  fontSize: { fontSize: 14 },
  icon: {
    backgroundColor: "#0F3D3E",
    borderRadius: 50,
  },
  inputNote: {
    width: "100%",
    padding: 9,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 5,
    marginBottom: 5,
    height: helpers.hp(15),
  },
  title: {
    fontSize: 18,
    fontFamily: PoppinsRegular,
    fontWeight: "500",
    marginVertical: 10,
  },
  subtitle: {
    fontSize: 12,
    color: "gray",
    marginBottom: 20,
  },
  input: {
    width: "100%",
    padding: 9,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 5,
  },
  buttonContainer: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
  },
  cancelButton: {
    flex: 1,
    padding: 10,
    backgroundColor: "#f0f0f0",
    alignItems: "center",
    borderRadius: 5,
    marginRight: 5,
  },
  cancelText: {
    color: "black",
  },
  addButton: {
    flex: 1,
    padding: 10,
    backgroundColor: "#0F3D3E",
    alignItems: "center",
    borderRadius: 5,
    marginLeft: 5,
  },
  addText: {
    color: "white",
  },
  attendanceSection: {
    marginTop: 20,
    padding: 15,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: PoppinsRegular,
    fontWeight: "500",
    marginBottom: 15,
    color: "#0F3D3E",
  },
  attendanceInfo: {
    gap: 10,
  },
  attendanceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e9ecef",
  },
  attendanceLabel: {
    fontSize: 14,
    fontFamily: PoppinsRegular,
    color: "#495057",
  },
  attendanceValue: {
    fontSize: 14,
    fontFamily: PoppinsRegular,
    color: "#212529",
    fontWeight: "500",
  },
  noAttendance: {
    textAlign: "center",
    color: "#6c757d",
    fontFamily: PoppinsRegular,
    fontSize: 14,
    paddingVertical: 15,
  },
  chartSection: {
    marginTop: 20,
    padding: 15,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  chartWrapper: {
    paddingHorizontal: 12,
    padding: 20,
    paddingBottom: 5,
  },
  yAxisTextStyle: {
    color: "#666",
    fontSize: 12,
    fontWeight: "400",
    margin: 0,
    top: -10,
    fontFamily: PoppinsRegular,
  },
  xAxisLabelTextStyle: {
    color: "#666",
    fontSize: 12,
    fontWeight: "400",
    fontFamily: PoppinsRegular,
    marginTop: 5,
  },
});
