export const POST_LOGIN_API = 'POST_LOGIN_API';
export const POST_ADD_CLASS_COMPONENT = 'POST_ADD_CLASS_COMPONENT';
export const DELETE_CLASS_COMPONENT = 'DELETE_CLASS_COMPONENT';
export const POST_LOGIN_OTP = 'POST_LOGIN_OTP';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_LOGIN_API = 'GET_LOGIN_API';
export const GET_USER_ROLE = 'GET_USER_ROLE';
export const GET_STUDENT_SEMESTER = 'GET_STUDENT_SEMESTER';
export const GET_COURSE_SCREEN = 'GET_COURSE_SCREEN';
export const UPDATE_CLASS_COMPONENT = 'UPDATE_CLASS_COMPONENT';
export const GET_SUBCOMPONENTS = 'GET_SUBCOMPONENTS';
export const SAVE_SUBCOMPONENTS = 'SAVE_SUBCOMPONENTS';
export const DELETE_SUBCOMPONENTS = 'DELETE_SUBCOMPONENTS';
export const EDIT_SUBCOMPONENTS = 'EDIT_SUBCOMPONENTS';
export const GET_COURSES_STUDENT_DATA = 'GET_COURSES_STUDENT_DATA';
export const GET_ATTENDENCE_DETAILS = 'GET_ATTENDENCE_DETAILS';
export const ATTENDENCE_SAVE = 'ATTENDENCE_SAVE';



