import { StyleSheet } from "react-native";
import { PoppinsRegular, PoppinsSemiBold } from "@/constants/fonts";

export const enhancedDropdownStyles = StyleSheet.create({
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.10)',
        zIndex: 9998,
    },
    dropdown: {
        position: "absolute",
        backgroundColor: "white",
        padding: 0,
        borderRadius: 16,
        minWidth: 340,
        elevation: 8,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.12,
        shadowRadius: 24,
        zIndex: 9999,
    },
    header: {
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        marginBottom: 0,
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        backgroundColor: '#fafbfc',
    },
    headerText: {
        fontSize: 18,
        fontFamily: PoppinsSemiBold,
        color: "#333",
        textAlign: "center",
        fontWeight: 'bold',
        letterSpacing: 0.2,
    },
    notificationItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        backgroundColor: '#fff',
        borderRadius: 10,
        marginBottom: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    notificationItemLast: {
        borderBottomWidth: 0,
        marginBottom: 0,
    },
    unreadDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: '#2563eb',
        marginRight: 14,
        marginTop: 6,
    },
    notificationTextContainer: {
        flex: 1,
        marginLeft: 8,
    },
    notificationTitle: {
        fontSize: 16,
        fontFamily: PoppinsSemiBold,
        color: '#222',
        marginBottom: 2,
        fontWeight: 'bold',
    },
    notificationBody: {
        fontSize: 14,
        fontFamily: PoppinsRegular,
        color: '#333',
        marginBottom: 2,
        flexShrink: 1,
    },
    timeAgo: {
        fontSize: 12,
        color: '#aaa',
        marginTop: 2,
    },
    emoji: {
        fontSize: 22,
        marginLeft: 8,
        marginTop: 4,
    },
}); 