export const icons: Record<string, { uri: string }> = {
  // arrowBack_Icon: require("./ba"),
  modalIconOtp: require("./modalotpIcon.png"),
  drawertabdashboardIcon: require("./element.png"),
  drawertabUsersIcon: require("./profile-2user.png"),
  drawertabLawIcon: require("./LAw.png"),
  drawertabnoteIcon: require("./note.png"),
  drawertabstarsupIcon: require("./status-up.png"),
  drawertabJobIcon: require("./job.png"),
  searchBarIcon: require("./search-normal.png"),
  profileHeaderBellIcon: require("./Vector.png"),
  tableDeleteIcon: require("./Trash can.png"),
  tableEditIcon: require("./Edit 1.png"),
  tableReadIcon: require("./Trash can copy.png"),
  tableStatusIcon: require("./_Badge base.png"),
  tableEyeIcon: require("./Eye.png"),
  tableDocumentIcon: require("./document-text.png"),
  screenHeaderPlusIcon: require("./Plus.png"),
  screenHeaderFilterIcon: require("./filter.png"),
  tablepaginationleftarrowIcon: require("./ArrowLineLeft2.png"),
  tablepaginationrightarrowIcon: require("./ArrowLineRight2.png"),
  editPencilicon: require("./edit-pencil.png"),
  documentDownloadIcon: require("./Download 2.png"),
  documendPdfIcon: require("./Frame 1686557330.png"),
  trendupIcon: require("./trend-up.png"),
  dashboardButtonNewscardIcon: require("./Frame 1597887482.png"),
  Drop_Down_Icon_Down: require("./Icon - Graphics.png"),
  HeaderFeedBackIcon: require("./Chat alt 2.png"),
  BottomHomeIcon: require("./pichome.png"),
  bottomChatIcon: require("./message.png"),
  bottomaddSquareIcon: require("./addsquare.png"),
  bottomThumSquareIcon: require("./shop.png"),
  bottomaddProfileIcon: require("./person-24.png"),
  ProfileIcon1: require("./Group 1686557625.png"),
  ProfileIcon2: require("./share.png"),
  ProfileIcon3: require("./Group.png"),
  ProfileIcon4: require("./Group2.png"),
  ProfileIcon5: require("./Frame.png"),
  ProfileIcon6: require("./Group3.png"),
};
